const aliens=[
  {
    "id": "1",
    "alien_name": "Sea Strider",
    "environment": "Amoebic Sea",
    "size": "Huge",
    "color": "Brown",
    "nature": "Calm",
    "photo": "path/to/photo",
    "leg_number": 2,

    "enemies": "fears nothing"
  },
  {
    "id": "2",
    "alien_name": "Grove-Back",
    "environment": "Plains",
    "size": "Huge",
    "color": "Tan",
    "nature": "Calm",
    "photo": "path/to/photo",
    "leg-number": 2,
    "enemies": "Beach Quills"
  },
  {
    "id": "3",
    "alien_name": "Eosapien",
    "environment": "Mountains",
    "size": "Medium",
    "color": "Purple",
    "nature": "Inquisitive",
    "photo": "path/to/photo",
    "leg-number": 0,
  },
  {
    "id": "4",
    "alien_name": "Arrowtongue",
    "environment": "Plains",
    "size": "Medium",
    "color": "Black",
    "nature": "Aggressive",
    "photo": "path/to/photo",
    "leg-number": 2,
  },
  {
    "id": "5",
    "alien_name": "Bladderhorn",
    "environment": "Mountains",
    "size": "Medium",
    "color": "Blue",
    "nature": "Territorial",
    "photo": "path/to/photo",
    "leg-number": 2,
  },
  {
    "id": "6",
    "alien_name": "Daggerwrist",
    "environment": "Forest",
    "size": "Medium",
    "color": "Orange",
    "nature": "Opportunist",
    "photo": "path/to/photo",
    "leg-number": 4,
  },
  {
    "id": "7",
    "alien_name": "Gyrosprinter",
    "environment": "Plains",
    "size": "Medium",
    "color": "Brown",
    "nature": "Flighty",
    "photo": "path/to/photo",
    "leg-number": 2,
  },
  {
    "id": "8",
    "alien_name": "Pronghead",
    "environment": "Beach",
    "size": "Medium",
    "color": "Orange",
    "nature": "Social",
    "photo": "path/to/photo",
    "leg-number": 2,
  },
  {
    "id": "9",
    "alien_name": "Skewer",
    "environment": "Plains",
    "size": "Big",
    "color": "Black",
    "nature": "Social",
    "photo": "path/to/photo",
    "leg-number": 0,
  },
  {
    "id": "10",
    "alien_name": "Unth",
    "environment": "Mountains",
    "size": "Medium",
    "color": "Light Orange",
    "nature": "Competitive",
    "photo": "path/to/photo",
    "leg-number": 2,
  }
]

export default { aliens }