import {ref} from "vue";

const aliens=[
  {
    "id": "1",
    "alien_name": "Sea Strider",
    "environment": "Amoebic Sea",
    "size": "Huge",
    "color": "Brown",
    "nature": "Calm",
    "photo": "/assets/sea-strider.png",
    "leg_number": 2,
    "enemies": "fears nothing"
  },
  {
    "id": "2",
    "alien_name": "Grove-Back",
    "environment": "Plains",
    "size": "Huge",
    "color": "Tan",
    "nature": "Calm",
    "photo": "../assets/images/grove-back.png",
    "leg-number": 2,
    "enemies": "Beach Quills"
  },
  {
    "id": "3",
    "alien_name": "Eosapien",
    "environment": "Mountains",
    "size": "Medium",
    "color": "Purple",
    "nature": "Inquisitive",
    "photo": "../assets/images/eosapien.png",
    "leg-number": 0,
  },
  {
    "id": "4",
    "alien_name": "Arrowtongue",
    "environment": "Plains",
    "size": "Medium",
    "color": "Black",
    "nature": "Aggressive",
    "photo": "../assets/images/arrow-tongue.png",
    "leg-number": 2,
  },
  {
    "id": "5",
    "alien_name": "Bladderhorn",
    "environment": "Mountains",
    "size": "Medium",
    "color": "Blue",
    "nature": "Territorial",
    "photo": "../assets/images/bladderhorn.png",
    "leg-number": 2,
  },
  {
    "id": "6",
    "alien_name": "Daggerwrist",
    "environment": "Forest",
    "size": "Medium",
    "color": "Orange",
    "nature": "Opportunist",
    "photo": "../assets/images/daggerwrist.png",
    "leg-number": 4,
  },
  {
    "id": "7",
    "alien_name": "Gyrosprinter",
    "environment": "Plains",
    "size": "Medium",
    "color": "Brown",
    "nature": "Flighty",
    "photo": "gyrosprinter",
    "leg-number": 2,
  },
  {
    "id": "8",
    "alien_name": "Pronghead",
    "environment": "Beach",
    "size": "Medium",
    "color": "Orange",
    "nature": "Social",
    "photo": "../assets/images/pronghead.png",
    "leg-number": 2,
  },
  {
    "id": "9",
    "alien_name": "Skewer",
    "environment": "Plains",
    "size": "Big",
    "color": "Black",
    "nature": "Social",
    "photo": "../assets/images/skewer.png",
    "leg-number": 0,
  },
  {
    "id": "10",
    "alien_name": "Unth",
    "environment": "Mountains",
    "size": "Medium",
    "color": "Light Orange",
    "nature": "Competitive",
    "photo": "../assets/images/unth.png",
    "leg-number": 2,
  }
]

export default { aliens }